- lib/entry.nunjucks.js
- lib/utils/template-wrapper.nunjucks.js
> Feat nprogress

- lib/entry.nunjucks.js
- package.json
解决 Object.assign 及下面的问题。
加上后，IE10/11 经测试可以访问。
> Add babel-polyfill

- lib/utils/template-wrapper.nunjucks.js
callback 带下来，我在组件里加NProgress...
> expose callback to collect

- README.md
react-amap is an [amap](http://lbs.amap.com/api/javascript-api/summary/) component based on React
> extend list built with bisheng

- .vscode/launch.json
- packages/bisheng-theme-one/package.json
- packages/bisheng/package.json
- packages/bisheng/src/utils/source-data.js
- packages/bisheng/test/utils/source-data.test.js
fix: https://github.com/ant-design/ant-design/issues/5452
ping @benjycui
> Refactor win support

- packages/bisheng/bin/bisheng-gh-pages
- packages/bisheng/src/index.js
for able to config  remote and branch options to gh-pages
> add remote and branch options to gh-pages

- README.md
- packages/bisheng/src/index.js
close https://github.com/benjycui/bisheng/issues/74
> feat: suport htmlTemplateExtraData

- packages/bisheng/package.json
- packages/bisheng/src/config/styleLoadersConfig.js
add scss support close: https://github.com/benjycui/bisheng/issues/101
> feat: add scss support, close: #101

- README.md
- packages/bisheng/package.json
- packages/bisheng/src/config/getStyleLoadersConfig.js
- packages/bisheng/src/config/updateWebpackConfig.js
- packages/bisheng/src/utils/get-bisheng-config.js
- packages/bisheng/test/fixtures/bisheng.config.js
- packages/bisheng/test/utils/get-config.test.js
> add postcssConfig

- packages/bisheng/src/index.js
Close https://github.com/ant-design/ant-design/issues/9554
> Enable minimize

- packages/bisheng/package.json
- packages/bisheng/src/config/getWebpackCommonConfig.js
- packages/bisheng/src/config/updateWebpackConfig.js
- packages/bisheng/src/index.js
- packages/bisheng/src/template.html
> feat: generate static file with hash

- .gitignore
- README.md
- packages/bisheng/src/config/getWebpackCommonConfig.js
- packages/bisheng/src/index.js
- packages/bisheng/src/template.html
https://github.com/ant-design/ant-design/issues/15925
```js
// bisheng.config.js
module.exports = {
...
hash: true,
...
}
```
```html
// user-defined template template.html
<head>
...
{% if hash %}
<link rel="stylesheet" type="text/css" href="{{ root }}{{ manifest['index.css'] }}"/>
{% else %}
<link rel="stylesheet" type="text/css" href="{{ root }}index.css"/>
{% endif %}
</head>
<body>
...
{% if hash %}
<script src="{{ root }}{{ manifest['index.js'] }}"></script>
{% else %}
<script src="{{ root }}index.js"></script>
{% endif %}
...
</body>
```
> Feat version ctx env

- packages/bisheng/src/config/getWebpackCommonConfig.js
- packages/bisheng/src/index.js
- packages/bisheng/src/template.html
```js
// bisheng.config.js
module.exports = {
...
hash: true,
...
}
```
```html
// user-defined template template.html
<body>
...
<script src="{{ root }}{{ manifest['index.js'] }}"></script>
...
</body>
```
> fix: remove entry css hash

- package.json
- packages/bisheng/package.json
- packages/bisheng/src/index.js
- packages/bisheng/src/ssr.nunjucks.jsx
- packages/bisheng/src/template.html
Close ant-design/ant-design/issues/16936
> Feat title support

- packages/bisheng/src/loaders/common/boss.js
> fix main process not exit when subprocess failed

- packages/bisheng-theme-one/package.json
- packages/bisheng-theme-one/src/template/Layout.jsx
- packages/bisheng-theme-one/src/template/NotFound.jsx
- packages/bisheng-theme-one/src/template/Post.jsx
- packages/bisheng/package.json
- packages/bisheng/src/ssr.nunjucks.jsx
https://github.com/ant-design/ant-design/pull/19643
> feat: support react-helmet-async

- packages/bisheng-plugin-toc/lib/node.js
@zombieJ 看下这里。我看了下报错，和bisheng-plugin-antd 关系不大，是bisheng-plugin-toc报的错导致编译出错的，只需要在JsonML getChildren之前先判断下类型再调用就可以了。 #226
> fix: determine before jml getChildren

- packages/bisheng-plugin-react/package.json
- packages/bisheng/package.json
close https://github.com/benjycui/bisheng/issues/223
https://github.com/ant-design/ant-design/pull/27268
> support React 17

- package.json
- packages/bisheng/package.json
> Remove postinstall of bisheng

- packages/bisheng/src/config/getStyleLoadersConfig.js
Change css-loader [modules option](https://github.com/webpack-contrib/css-loader/releases/tag/v3.0.0)
> fix: change css-loader modules option

- .gitignore
- packages/bisheng-plugin-react/README.md
- packages/bisheng-plugin-react/lib/transformer.js
- packages/bisheng-plugin-react/test/node.test.js
support `export default` in jsx
> feat(bisheng-plugin-react): support export default

- packages/bisheng/src/entry.nunjucks.jsx
根据版本自动切换方法：
ref https://github.com/ant-design/ant-design/pull/34787
> chore: Use react-18 render if possible

- packages/bisheng/src/ssr.nunjucks.jsx
> fix: html title for ssr
